BEGIN TRANSACTION;

DELETE FROM osis_to_detailed_name;

INSERT INTO osis_to_detailed_name
    (osis, book_order, short_name, long_name, testament)
VALUES
('GEN',  1, 'Gen',  'Genesis',        'OT'),
('EXO',  2, 'Exod', 'Exodus',         'OT'),
('LEV',  3, 'Lev',  'Leviticus',      'OT'),
('NUM',  4, 'Num',  'Numbers',        'OT'),
('DEU',  5, 'Deut', 'Deuteronomy',    'OT'),
('JOS',  6, 'Josh', 'Joshua',         'OT'),
('JDG',  7, 'Judg', 'Judges',         'OT'),
('RUT',  8, 'Ruth', 'Ruth',            'OT'),
('1SA',  9, '1Sam', '1 Samuel',        'OT'),
('2SA', 10, '2Sam', '2 Samuel',        'OT'),
('1KI', 11, '1Kgs', '1 Kings',         'OT'),
('2KI', 12, '2Kgs', '2 Kings',         'OT'),
('1CH', 13, '1Chr', '1 Chronicles',    'OT'),
('2CH', 14, '2Chr', '2 Chronicles',    'OT'),
('EZR', 15, 'Ezra', 'Ezra',            'OT'),
('NEH', 16, 'Neh',  'Nehemiah',        'OT'),
('EST', 17, 'Esth', 'Esther',          'OT'),
('JOB', 18, 'Job',  'Job',             'OT'),
('PSA', 19, 'Ps',   'Psalms',          'OT'),
('PRO', 20, 'Prov', 'Proverbs',        'OT'),
('ECC', 21, 'Eccl', 'Ecclesiastes',    'OT'),
('SNG', 22, 'Song', 'Song of Songs',   'OT'),
('ISA', 23, 'Isa',  'Isaiah',          'OT'),
('JER', 24, 'Jer',  'Jeremiah',        'OT'),
('LAM', 25, 'Lam',  'Lamentations',    'OT'),
('EZK', 26, 'Ezek', 'Ezekiel',          'OT'),
('DAN', 27, 'Dan',  'Daniel',           'OT'),
('HOS', 28, 'Hos',  'Hosea',            'OT'),
('JOL', 29, 'Joel', 'Joel',             'OT'),
('AMO', 30, 'Amos', 'Amos',             'OT'),
('OBA', 31, 'Obad', 'Obadiah',          'OT'),
('JON', 32, 'Jonah','Jonah',            'OT'),
('MIC', 33, 'Mic',  'Micah',            'OT'),
('NAM', 34, 'Nah',  'Nahum',            'OT'),
('HAB', 35, 'Hab',  'Habakkuk',         'OT'),
('ZEP', 36, 'Zeph', 'Zephaniah',        'OT'),
('HAG', 37, 'Hag',  'Haggai',           'OT'),
('ZEC', 38, 'Zech', 'Zechariah',        'OT'),
('MAL', 39, 'Mal',  'Malachi',          'OT'),
('MAT', 40, 'Matt', 'Matthew',          'NT'),
('MRK', 41, 'Mark', 'Mark',             'NT'),
('LUK', 42, 'Luke', 'Luke',             'NT'),
('JHN', 43, 'John', 'John',             'NT'),
('ACT', 44, 'Acts', 'Acts',             'NT'),
('ROM', 45, 'Rom',  'Romans',           'NT'),
('1CO', 46, '1Cor', '1 Corinthians',    'NT'),
('2CO', 47, '2Cor', '2 Corinthians',    'NT'),
('GAL', 48, 'Gal',  'Galatians',        'NT'),
('EPH', 49, 'Eph',  'Ephesians',        'NT'),
('PHP', 50, 'Phil', 'Philippians',      'NT'),
('COL', 51, 'Col',  'Colossians',       'NT'),
('1TH', 52, '1Th',  '1 Thessalonians',  'NT'),
('2TH', 53, '2Th',  '2 Thessalonians',  'NT'),
('1TI', 54, '1Tim', '1 Timothy',        'NT'),
('2TI', 55, '2Tim', '2 Timothy',        'NT'),
('TIT', 56, 'Titus','Titus',            'NT'),
('PHM', 57, 'Phlm', 'Philemon',         'NT'),
('HEB', 58, 'Heb',  'Hebrews',          'NT'),
('JAS', 59, 'Jas',  'James',            'NT'),
('1PE', 60, '1Pet', '1 Peter',          'NT'),
('2PE', 61, '2Pet', '2 Peter',          'NT'),
('1JO', 62, '1Jn',  '1 John',            'NT'),
('2JO', 63, '2Jn',  '2 John',            'NT'),
('3JO', 64, '3Jn',  '3 John',            'NT'),
('JUD', 65, 'Jude', 'Jude',              'NT'),
('REV', 66, 'Rev',  'Revelation',        'NT');

COMMIT;